### ISSUE TITLE
Crashing Node-Red - Uncaught Exception

### ISSUE THREAD

**Issue by Unpuertomex** [Hypnos3/node-red-contrib-cast#12]
Hi, I'm running into a situation in which the cast node is constantly crashing node-red. The payload that is being sent is very simple {"payload":"Tommy made it home safely"}, it processes the information and about a minute or so crashes node-red.
node-red v0.19.4
node.js v.8.12.0

15 Oct 07:22:46 - [red] Uncaught Exception:
15 Oct 07:22:46 - ReferenceError: node is not defined
at client.launch (C:\Users\unpue.node-red\node_modules\node-red-contrib-cast\cast-to-client.js:73:13)
at C:\Users\unpue.node-red\node_modules\castv2-client\lib\senders\platform.js:95:20
at C:\Users\unpue.node-red\node_modules\castv2-client\lib\controllers\receiver.js:51:14
at fn.onmessage (C:\Users\unpue.node-red\node_modules\castv2-client\lib\controllers\request-response.js:27:7)
at emitTwo (events.js:131:20)
at fn.emit (events.js:214:7)
at Channel.onmessage (C:\Users\unpue.node-red\node_modules\castv2-client\lib\controllers\controller.js:16:10)
at emitTwo (events.js:126:13)
at Channel.emit (events.js:214:7)
at Client.onmessage (C:\Users\unpue.node-red\node_modules\castv2\lib\channel.js:23:10)
at emitMany (events.js:152:20)
at Client.emit (events.js:224:7)
at PacketStreamWrapper.onpacket (C:\Users\unpue.node-red\node_modules\castv2\lib\client.js:81:10)
at emitOne (events.js:116:13)
at PacketStreamWrapper.emit (events.js:211:7)
at TLSSocket. (C:\Users\unpue.node-red\node_modules\castv2\lib\packet-stream-wrapper.js:28:16)
at emitNone (events.js:106:13)
at TLSSocket.emit (events.js:208:7)
at emitReadable (_stream_readable.js:513:10)
at emitReadable (_stream_readable.js:507:7)
at addChunk (_stream_readable.js:274:7)
at readableAddChunk (_stream_readable.js:250:11)

**Comment by Paul-Reed** [comment]
@Hypnos3 - see https://discourse.nodered.org/t/node-red-crashing-could-it-be-node-red-contrib-cast/4014/5

**Comment by Hypnos3** [comment]
On my side the node is runninge stable, so I'm currently searching a way to reproduce the crash to be able to fit it.

**Comment by Hypnos3** [comment]
I have changed several. Can you please check Version 0.0.9?

**Comment by Hypnos3** [comment]
I think I have found the problem and released version 0.1.0 which should fix this crash.

**Comment by Hypnos3** [comment]
OK, this is a response from the underlying library and as far as I understand comes the response "Load cancelled" direct from the device.

at [Google documentation](https://developers.google.com/cast/docs/reference/messages) is stated:
Sent when the load request was cancelled (a second load request was received).

**Comment by Unpuertomex** [comment]
Read it and I think I understand now. I believe you can close this one. Thank for your quick response!!

**Comment by Hypnos3** [comment]
Thank you!
