### ISSUE TITLE
Exception when attempting to get the status of a Chromecast Audio

### ISSUE THREAD

**Issue by S1MP50N** [Hypnos3/node-red-contrib-cast#22]
Hi,

When I attempt to get the status of a chromecast Audio, which is not doing anything, I get the following exception:

"Exception occured on load media:Cannot read property 'transportId' of undefined"

Is this expected behaviour? I assumed that the status message would come back even though no application is present. When the chromecast Audio is casting (such as spotify) it appears to work correctly and I get a status message.

Thanks for your great work.

**Comment by S1MP50N** [comment]
I should add this is the latest NPM version. As pulled down 2 hours ago.

**Comment by deonp** [comment]
I get the same issue with my Google Home's

**Comment by Hypnos3** [comment]
I can adjust the error. It occurs in the underlying library castv2 and always occurs when one tries to retrieve the status and before there is no connection to the cast device. If an audio file was output only once, the error does not occur.

Further investigations will take some time.

Here the stack trace of the error:
```
18 Nov 15:23:20 - [debug] [cast-to-client:82e3c67a.27b218] start playing on cast device
18 Nov 15:23:20 - [debug] [cast-to-client:82e3c67a.27b218] {"language":"en","ip":"192.168.178.35","delay":250}
18 Nov 15:23:20 - [debug] [cast-to-client:82e3c67a.27b218] only sending unspecified request to ip='192.168.178.35'
18 Nov 15:23:20 - [debug] [cast-to-client:82e3c67a.27b218] connect to client ip='192.168.178.35'
18 Nov 15:23:20 - [debug] [cast-to-client:82e3c67a.27b218] session: undefined
18 Nov 15:23:20 - [error] [cast-to-client:82e3c67a.27b218] Exception occured on load media:Cannot read property 'transportId' of undefined
18 Nov 15:23:20 - [debug] [cast-to-client:82e3c67a.27b218] {"stack":"TypeError: Cannot read property 'transportId' of undefined\n    at DefaultMediaReceiver.Application (C:\\Users\\post\\.node-red\\node_modules\\castv2-client\\lib\\senders\\application.js:7:55)\n    at new DefaultMediaReceiver (C:\\Users\\post\\.node-red\\node_modules\\castv2-client\\lib\\senders\\default-media-receiver.js:7:15)\n    at PlatformSender.join (C:\\Users\\post\\.node-red\\node_modules\\castv2-client\\lib\\senders\\platform.js:88:18)\n    at C:\\Users\\post\\.node-red\\node_modules\\node-red-contrib-cast\\cast-to-client.js:218:28\n    at C:\\Users\\post\\.node-red\\node_modules\\castv2-client\\lib\\controllers\\receiver.js:86:5\n    at C:\\Users\\post\\.node-red\\node_modules\\castv2-client\\lib\\controllers\\receiver.js:31:5\n    at fn.onmessage (C:\\Users\\post\\.node-red\\node_modules\\castv2-client\\lib\\controllers\\request-response.js:27:7)\n    at emitTwo (events.js:131:20)\n    at fn.emit (events.js:214:7)\n    at Channel.onmessage (C:\\Users\\post\\.node-red\\node_modules\\castv2-client\\lib\\controllers\\controller.js:16:10)","message":"Cannot read property 'transportId' of undefined"}
18 Nov 15:23:21 - [debug] [cast-to-client:1aeaf7fe.76f718] start playing on cast device
18 Nov 15:23:21 - [debug] [cast-to-client:1aeaf7fe.76f718] {"language":"en","ip":"192.168.178.35","delay":250}
18 Nov 15:23:21 - [debug] [cast-to-client:1aeaf7fe.76f718] only sending unspecified request to ip='192.168.178.35'
18 Nov 15:23:21 - [debug] [cast-to-client:1aeaf7fe.76f718] connect to client ip='192.168.178.35'
18 Nov 15:23:21 - [debug] [cast-to-client:1aeaf7fe.76f718] session: undefined
18 Nov 15:23:21 - [error] [cast-to-client:1aeaf7fe.76f718] Exception occured on load media:Cannot read property 'transportId' of undefined
18 Nov 15:23:21 - [debug] [cast-to-client:1aeaf7fe.76f718] {"stack":"TypeError: Cannot read property 'transportId' of undefined\n    at DefaultMediaReceiver.Application (C:\\Users\\post\\.node-red\\node_modules\\castv2-client\\lib\\senders\\application.js:7:55)\n    at new DefaultMediaReceiver (C:\\Users\\post\\.node-red\\node_modules\\castv2-client\\lib\\senders\\default-media-receiver.js:7:15)\n    at PlatformSender.join (C:\\Users\\post\\.node-red\\node_modules\\castv2-client\\lib\\senders\\platform.js:88:18)\n    at C:\\Users\\post\\.node-red\\node_modules\\node-red-contrib-cast\\cast-to-client.js:218:28\n    at C:\\Users\\post\\.node-red\\node_modules\\castv2-client\\lib\\controllers\\receiver.js:86:5\n    at C:\\Users\\post\\.node-red\\node_modules\\castv2-client\\lib\\controllers\\receiver.js:31:5\n    at fn.onmessage (C:\\Users\\post\\.node-red\\node_modules\\castv2-client\\lib\\controllers\\request-response.js:27:7)\n    at emitTwo (events.js:131:20)\n    at fn.emit (events.js:214:7)\n    at Channel.onmessage (C:\\Users\\post\\.node-red\\node_modules\\castv2-client\\lib\\controllers\\controller.js:16:10)","message":"Cannot read property 'transportId' of undefined"}
```

**Comment by Hypnos3** [comment]
I had released Version 0.2.0, which should fix that Bug. Unfortunately, I could only limited test all cases.

**Comment by S1MP50N** [comment]
Hi Hypnos3,

Apologies for the delay in reply (emails in junk, just spotted them). Thanks for the quick support. I will grab the new version later tonight and give it a test. :+1:

**Comment by S1MP50N** [comment]
Hi Hypnos3, 

I can confirm that has resolved my issue and I get back an empty application status. Thank you for the quick fix.
