### ISSUE TITLE
Exception when Group Casting to Chromecast Audio

### ISSUE THREAD

**Issue by S1MP50N** [Hypnos3/node-red-contrib-cast#24]
Hi Again,

Was just doing some further testing and found another scenario where an exception is raised. This time when casting to a cast group and attempting to get the status of a chromecast. 

`"Exception occured on load media test:Illegal value for Message.Field .extensions.api.cast_channel.CastMessage.destination_id of type string: undefined (not a string)"`

I did a bit of debugging with some local modifications to catch the callstack:

```
Error: Illegal value for Message.Field .extensions.api.cast_channel.CastMessage.destination_id of type string: undefined (not a string)
    at Error (native)
    at T.<anonymous> (/data/node_modules/protobufjs/dist/ProtoBuf.js:2641:27)
    at T.ProtoBuf.Reflect.FieldPrototype.verifyValue (/data/node_modules/protobufjs/dist/ProtoBuf.js:2721:29)
    at MessagePrototype.set (/data/node_modules/protobufjs/dist/ProtoBuf.js:1799:63)
    at Message (/data/node_modules/protobufjs/dist/ProtoBuf.js:1725:42)
    at Object.serialize (/data/node_modules/castv2/lib/proto.js:18:17)
    at Client.send (/data/node_modules/castv2/lib/client.js:127:25)
    at Channel.send (/data/node_modules/castv2/lib/channel.js:34:12)
    at ConnectionController.Controller.send (/data/node_modules/castv2-client/lib/controllers/controller.js:28:16)
    at ConnectionController.connect (/data/node_modules/castv2-client/lib/controllers/connection.js:28:8)
```

This appears to be outside your domain in the linked cast libs but thought I would raise for completeness. May also be related to #20 

Thanks,

**Comment by Hypnos3** [comment]
yes this is releated to #20 
Since I have only one google home I can not test the groups and therefore it is difficult for me to mimic the error.

**Comment by Hypnos3** [comment]
should be already fixed
